const language = [ 
    // English 
    { 	
		'repeatyournewemail':'Repeat your New E-mail',
		'enteryournewemail':'Enter your New E-mail',
		'changeemail':'Change E-mail',
		'repeatyournewpassword':'Repeat your New Password',
		'enteryournewpassword':'Enter your New Password',
		'enteryouroldpassword':'Enter your Old Password',
		'changepassword':'Change Password',
		'repeatyournewphonenumber':'Repeat your New Phone Number',
		'enteryournewphonenumber':'Enter your New Phone Number',
		'changephonenumber':'Change Phone Number',
		'repeatyournewusername':'Repeat your New Username',
		'enteryournewusername':'Enter your New Username',
		'changeusername':'Change Username',
		'oldpasswordnotcorrect':'Old Password not correct!',
		'fieldsnotequalinpassword':'Fields not equal in Password!',
		'emptyinputfieldsinpassword':'Empty input fields in Password!',
		'passwordupdatedcorrectly':'Password updated correctly!',
		'fieldsnotequalinemail':'Fields not equal in E-mail!',
		'emptyinputfieldsinemail':'Empty input fields in E-mail!',
		'emailupdatedcorrectly':'E-mail updated correctly!',
		'fieldsnotequalinphonenumber':'Fields not equal in Phone Number!',
		'emptyinputfieldsinphonenumber':'Empty input fields in Phone Number!',
		'phonenumberupdatedcorrectly':'Phone number updated correctly!',
		'fieldsnotequalinusername':'Fields not equal in Username!',
		'emptyinputfieldsinusername':'Empty input fields in Username!',
		'usernameupdatedcorrectly':'Username updated correctly!',
		'verify':'Verify',
		'coursedescription':'Course Description',
		'qualifications':'Qualifications',
		'noexercisesassigned':'No exercises assigned.',
		'finished':'Finished',
		'puntuation':'Puntuation',
		'exercise':'Exercise',
		'createtheory':'Create Theory',
		'answers':'Answers',
		'incorrect':'Incorrect!',
		'correct':'Correct!',
		'tries':'Tries',
		'enrollexcelstudents':'Enroll Excel Students',
		'loadxlsxfile':'Load xlsx file',
		'downloadtemplate':'Download Template',
		'loadusersfromexcel':'Load Users From Excel',
		'enrollselectedstudents':'Enroll Selected Students',
		'selectall':'Select all',
		'enrollstudents':'Enroll Students',
		'enroll':'Enroll',
		'newstudent':'New Student?',
		'name':'Name',
		'surname':'Surname',
		'username':'Username',
		'enrolledusers':'Enrolled users!',
		'addanswer':'Add answer',
		'answersnotset':'Answers not set',
		'selectionexercise':'Selection Exercise',
		'radius':'Radius',
		'center':'Center',
		'sagital':'Sagittal',
		'openset':'Open set',
		'library':'Library',
		'selectfromlibrary':'Select from library',
		'models':'Models',
		'solutionmodels':'Solution Models',
		'addtosolution':'Add to solution',
		'deletee':'Delete',
		'enterexercisestatement':'Enter Exercise Statement',
		'modelnotset':'Model not set',
		'maximumtries':'Maximum Tries',
		'helptext':'Help Text',
		'textsolution':'Text Solution',
		'question':'Question',
		'imagenotset':'Image not set',
		'helpnotset':'Help not set',
		'questionnotset':'Question not set',
		'descriptionnotset' :'Description not set',
		'titlenotset':'Title not set',
		'topicsnotselected':'Topics not selected',
		'maximumtriesnotvalid':'Maximum tries not valid',
		'difficultynotvalid':'Difficulty not valid',
		'titlealreadyexists':'Title already exists',
		'labellingexercise':'Labelling Exercise',
		'emptyinputfieldsinpasswordrecovery':'Empty input fields in password recovery!',
		'emptyinputfieldsinlogin':'Empty input fields in login!',
		'usernameorpasswordinvalid':'Username or Password invalid!',
		'chooseexercise':'Choose Exercise',
		'animationexercise':'Animation Exercise',
		'createcourse':'Create Course',
		'difficulty':'Difficulty',
		'coursetype':'Course Type',
		'prerequisits':'Pre-Requisits',
		'description':'Description',
		'categories':'Categories',
		'search':'Search',
		'entercoursetitle':'Enter Course Title',
		'topics':'Topics',
		'deleteimage':'Delete Image',
		'content':'Content',
		'url':'URL',
		'entertheorysubtitle':'Enter Theory Subtitle',
		'entertheorytitle':'Enter Theory Title',
		'notopicsincourse':'There are no topics in this course.',
		'createnewtheory':'Create New Theory',
		'createnewexercise':'Create New Exercise',
		'createnewcourse':'Create New Course',
		'currentcourses':'Current Courses',
        'register': 'Register', 
		'partialpenalty': 'Partial Penalty',
		'fullpenalty' : 'Full Penalty',
		'login' : 'Login', 
		'assignexercises' :'Assign Exercises',
		'exercises' : 'Exercises',
		'from':'From',
		'time' : 'Time',
		'selection' :'Selection',
		'elearningplatform' : 'E-Learning Platform',
		'profile' : 'Profile',
		'animation' : 'Animation',
		'nopenalty':'No Penalty',
		'labelling' : 'Labelling',
		'to':'To',
		'addexercises' : 'Add Exercises',
		'strategy' : 'Strategy',
		'courses' : 'Courses',
		'students' : 'Students',
		'registernow':'Register Now',
		'registerintro' : 'This is a platform made with the purpouse of teaching topics as Radiology, CPR and anatomy among others. GILAB, is a research group of the University of Girona (with code GRCT0081) and all researchers of the GIlab are from the Computer Science, Applied Mathematics and Statistics Department at the same university.',
		'continue':'Continue',
		'mpr' : 'MPR',
		'enterrepeatpassword' : 'Repeat your Password',
		'enterasguest' : 'Enter as Guest',
		'enteremail' : "Enter your e-mail",
		'admin' : 'Admin',
		'attemp' : 'Attemps',
		'logout' : 'Logout',
		'enterpassword' : "Enter your Password",
		'enterusername' : 'Enter your Username',
		'forgotpassword' : 'Forgot Password?',
		'test2d' : 'Test 2D',
		'chooseexercisetype' : 'Choose Exercise Type',
		'image2d' : '2d Image',
		'image3d' : '3d Image',
        'cookies': "We use cookies to ensure that we give you the best experience on our website. We also use cookies to ensure we show you advertising that is relevant to you. If you continue without changing your settings, we'll assume that you are happy to receive all cookies on the website.", 
    }, 
    // Catala
    {
		'repeatyournewemail':'Repeteix correu electrònic',
		'enteryournewemail':'Nou correu electrònic',
		'changeemail':'Canviar e-mail',
		'repeatyournewpassword':'Repeteix contrasenya nova',
		'enteryournewpassword':'Contrasenya nova',
		'enteryouroldpassword':'Contrasenya antiga',
		'changepassword':'Canvia la contrasenya',
		'repeatyournewphonenumber':'Repeteix nou número de telèfon',
		'enteryournewphonenumber':'Nou número de telèfon',
		'changephonenumber':'Canviar el número de telèfon',
		'repeatyournewusername':"Repeteix el nom d'usuari",
		'enteryournewusername':"Nou nom d'usuari",
		'changeusername':"Canviar nom d'usuari",
		'oldpasswordnotcorrect':'Contrasenya antiga no correcta.',
		'fieldsnotequalinpassword':'Els camps no són iguals a la contrasenya.',
		'emptyinputfieldsinpassword':"Camps d'entrada buits a la contrasenya!",
		'passwordupdatedcorrectly':'Contrasenya actualitzada correctament!',
		'fieldsnotequalinemail':'Els camps no són iguals a E-mail!',
		'emptyinputfieldsinemail':"Camps d'entrada buits a E-mail!",
		'emailupdatedcorrectly':"El correu electrònic s'ha actualitzat correctament.",
		'fieldsnotequalinphonenumber':'Els camps no són iguals al número de telèfon!',
		'emptyinputfieldsinphonenumber':"Camps d'entrada buits al número de telèfon!",
		'phonenumberupdatedcorrectly':"El número de telèfon s'ha actualitzat correctament!",
		'fieldsnotequalinusername':"Els camps no són iguals al nom d'usuari!",
		'emptyinputfieldsinusername':"Camps d'entrada buits al nom d'usuari!",
		'usernameupdatedcorrectly':"El nom d'usuari s'ha actualitzat correctament!",
		'verify':'Corregir',
		'coursedescription':'Descripció del curs',
		'qualifications':'Qualificacions',
		'noexercisesassigned':'No hi han exercicis assignats.',
		'finished':'Acabat',
		'puntuation':'Puntuació',
		'exercise':'Exercici',
		'createtheory':'Crear teoria',
		'answers':'Respostes',
		'incorrect':'Incorrecte!',
		'correct':'Correcte!',
		'tries':'Intents',
		'enrollexcelstudents':"Matricular estudiants de l'excel",
		'loadxlsxfile':'Carregar fitxer xlsx',
		'downloadtemplate':'Baixar la plantilla',
		'loadusersfromexcel':'Carregar usuaris de excel',
		'enrollselectedstudents':'Matricular estudiants seleccionats',
		'selectall':'Seleccionar tot',
		'enrollstudents':'Matricular alumnes',
		'enroll':'Matricular',
		'newstudent':'Estudiant nou?',
		'name':'Nom',
		'surname':'Cognom',
		'username':'Usuari',
		'enrolledusers':'Usuaris inscrits!',
		'addanswer':'Afegir resposta',
		'answersnotset':'Respostes no existents',
		'selectionexercise':'Exercici de selecció',
		'radius':'Radi',
		'center':'Centre',
		'sagital':'Sagital',
		'openset':'Obrir conjunt',
		'library':'Biblioteca',
		'selectfromlibrary':'Escull de la biblioteca',
		'models':'Models',
		'solutionmodels':'Models solució',
		'addtosolution':'Afegir a solució',
		'deletee':'Eliminar',
		'enterexercisestatement':"Introduïu el títol de l'exercici",
		'modelnotset':'Model no existent',
		'maximumtries':"Màxim d'intents",
		'helptext':"Text d'ajuda",
		'textsolution':'Solució de text',
		'question':'Pregunta',
		'imagenotset':'Imatge no existent',
		'helpnotset':'Ajuda no existent',
		'questionnotset':'Pregunta no existent',
		'descriptionnotset' :'Descripció no existent',
		'titlenotset':'Títol no existent',
		'topicsnotselected':'Topics no seleccionats',
		'maximumtriesnotvalid':"El màxim d'intents no és vàlid",
		'difficultynotvalid':'Dificultat no vàlida',
		'titlealreadyexists':'El títol ja existeix',
		'labellingexercise':"Exercici d'etiquetatge",
		'emptyinputfieldsinpasswordrecovery':"Camps d'entrada buits a la recuperació de la contrasenya!",
		'emptyinputfieldsinlogin':"Camps d'entrada buits al inici de sessió!",
		'usernameorpasswordinvalid':"El nom d'usuari o la contrasenya no són vàlids!",
		'chooseexercise':"Trieu l'exercici",
		'animationexercise':"Exercici d'animació",
		'createcourse':'Crear Curs',
		'difficulty':'Dificultat',
		'coursetype':'Tipus de curs',
		'prerequisits':'Requisits previs',
		'description':'Descripció',
		'categories':'Categories',
		'search':'Cerca',
		'entercoursetitle':'Introduïu el títol del curs',
		'topics':'Topics',
		'deleteimage':'Eliminar imatge',
		'content':'Contingut',
		'url':'URL',
		'entertheorysubtitle':'Introduïu el subtítol de la teoria',
		'entertheorytitle':'Introduïu el títol de la teoria',
		'notopicsincourse':'No hi han topics en aquest curs.',
		'createnewtheory':'Crear nova teoria',
		'createnewexercise':'Crear nou exercici',
		'createnewcourse':'Crear curs nou',
		'currentcourses':'Cursos actuals',
        'register': "Registra't", 
		'continue':'Continuar',
		'selection' :'Selecció',
		'animation' : 'Animació',
		'exercises' : 'Exercicis',
		'time' : 'Temps',
		'labelling' : 'Etiquetatge',
		'mpr' : 'MPR',
		'image2d' : 'Imatge 2D',
		'to':'a',
		'chooseexercisetype' : "Trieu el tipus d'exercici",
		'image3d' : '3d Image',
		'test2d' : 'Test 2D',
		'from':'des de',
		'strategy' : 'Estratègia',
		'addexercises' : 'Afegir exercicis',
		'attemp' : 'Intents',
		'login' : 'Iniciar Sessió',
		'assignexercises' :'Assignar Exercicis',
		'fullpenalty' : 'Penalització complerta',
		'partialpenalty': 'Penalització parcial',		
		'logout' : 'Tancar Sessió',
		'admin' : 'Administrador',
		'students' : 'Estudiants',
		'profile' : 'Perfil',
		'nopenalty':'Sense penalització',
		'courses' : 'Cursos',
		'elearningplatform' : 'Plataforma E-Learning',
		'registernow':"Registra't ara",
		'enterasguest' : 'Entrar com a convidat',
		'enterusername' : "Introdueix l'usuari",
		'registerintro' : "Es tracta d'una plataforma elaborada amb el purpòsit de temes d'ensenyament com la radiologia, la RCP i l'anatomia entre d'altres. GILAB, és un grup de recerca de la Universitat de Girona (amb el codi GRCT0081) i tots els investigadors del GIlab són del Departament d'Informàtica, Matemàtica Aplicada i Estadística de la mateixa universitat.",
		'enteremail' : "Introdueix el seu e-mail",
		'enterpassword' : "Introdueix la contrasenya",
		'enterrepeatpassword' : 'Repeteix la contrasenya',
		'forgotpassword' : 'Has oblidat la contrasenya?',
        'cookies': 'Utilitzem cookies per assegurar-nos que us donem la millor experiència al nostre lloc web. També fem servir cookies per assegurar-nos que us mostrem publicitat que sigui rellevant per a vosaltres. Si continueu sense canviar la vostra configuració, suposarem que us alegrareu de rebre totes les cookies del lloc web.', 
    }, 
    // Castellano
    { 
		'repeatyournewemail':'Repite correo electrónico',
		'enteryournewemail':'Ingrese correo electrónico',
		'changeemail':'Cambiar e-mail',
		'repeatyournewpassword':'Repite nueva contraseña',
		'enteryournewpassword':'Ingrese nueva contraseña',
		'enteryouroldpassword':'Ingrese contraseña anterior',
		'changepassword':'Cambia la contraseña',
		'repeatyournewphonenumber':'Repite número de teléfono',
		'enteryournewphonenumber':'Ingrese número de teléfono',
		'changephonenumber':'Cambiar número de teléfono',
		'repeatyournewusername':'Repite nombre de usuario',
		'enteryournewusername':'Ingrese nombre de usuario',
		'changeusername':"Cambiar nombre de usuario",
		'oldpasswordnotcorrect':'¡La contraseña anterior no es correcta!',
		'fieldsnotequalinpassword':'¡Los campos no son iguales en la contraseña!',
		'emptyinputfieldsinpassword':'¡Campos de entrada vacíos en Contraseña!',
		'passwordupdatedcorrectly':'Contraseña actualizada correctamente!',
		'fieldsnotequalinemail':'¡Los campos no son iguales en el correo electrónico!',
		'emptyinputfieldsinemail':"¡Campos de entrada vacíos en el correo electrónico!",
		'emailupdatedcorrectly':'¡Correo electrónico actualizado correctamente!',
		'fieldsnotequalinphonenumber':'¡Los campos no son iguales en el número de teléfono!',
		'emptyinputfieldsinphonenumber':'¡Campos de entrada vacíos en el número de teléfono!',
		'phonenumberupdatedcorrectly':'¡Número de teléfono actualizado correctamente!',
		'fieldsnotequalinusername':'¡Los campos no son iguales en el nombre de usuario!',
		'emptyinputfieldsinusername':'¡Campos de entrada vacíos en el nombre de usuario!',
		'usernameupdatedcorrectly':'¡Nombre de usuario actualizado correctamente!',
		'verify':'Corregir',
		'coursedescription':'Descripción del curso',
		'qualifications':'Cualificaciones',
		'noexercisesassigned':'No hay ejercicios asignados.',
		'finished':'Terminado',
		'puntuation':'Puntuación',
		'exercise':'Ejercicio',
		'createtheory':'Crear teoría',
		'answers':'Respuestas',
		'incorrect':'¡Incorrect!',
		'correct':'¡Correcto!',
		'tries':'Intentos',
		'enrollexcelstudents':"Matricular estudiantes del excel",
		'loadxlsxfile':'Cargar archivo xlsx',
		'downloadtemplate':'Descargar la plantilla',
		'loadusersfromexcel':'Cargar usuarios de excel',
		'enrollselectedstudents':'Matricular estudiantes seleccionados',
		'selectall':'Seleccionar todo',
		'enrollstudents':'Matricular alumnos',
		'enroll':'Matricular',
		'newstudent':'¿Estudiante nuevo?',
		'name':'Nombre',
		'surname':'Apellido',
		'username':'Usuario',
		'enrolledusers':'Usuarios inscritos!',
		'addanswer':'Añadir respuesta',
		'answersnotset':'Respuestas no existentes',
		'selectionexercise':'Ejercicio de selección',
		'radius':'Radio',
		'center':'Centro',
		'sagital':'Sagital',
		'openset':'Abrir conjunto',
		'library':'Biblioteca',
		'selectfromlibrary':'Seleccionar de la biblioteca',
		'models':'Modelos',
		'solutionmodels':'Modelos solución',
		'addtosolution':'Añadir a solución',
		'deletee':'Eliminar',
		'enterexercisestatement':"Introduzca el título del ejercicio",
		'modelnotset':'Modelo no existente',
		'maximumtries':"Máximo de intentos",
		'helptext':'Texto de ayuda',
		'textsolution':'Solución de texto',
		'question':'Pregunta',
		'imagenotset':'Imagen no existente',
		'helpnotset':'Ayuda no existente',
		'questionnotset':'Pregunta no existente',
		'descriptionnotset' :'Descripción no existente',
		'titlenotset':'Título no existente',
		'topicsnotselected':'Temas no seleccionados',
		'maximumtriesnotvalid':"El máximo de intentos no es válido",
		'difficultynotvalid':'Dificultad no válida',
		'titlealreadyexists':'El título ya existe',
		'labellingexercise':"Ejercicio de etiquetado",
		'emptyinputfieldsinpasswordrecovery':'¡Campos de entrada vacíos en la recuperación de contraseña!',
		'emptyinputfieldsinlogin':'¡Campos de entrada vacíos en el inicio de sesión!',
		'usernameorpasswordinvalid':"¡Nombre de usuario o contraseña inválidos!",
		'chooseexercise':"Elige ejercicio",
		'animationexercise':'Ejercicio de animación',
		'createcourse':'Crear Curso',
		'difficulty':'Dificultad',
		'coursetype':'Tipo de curso',
		'prerequisits':'Requisitos previos',
		'description':'Descripción',
		'categories':'Categorías',
		'search':'Buscar',
		'entercoursetitle':'Ingrese el título del curso',
		'topics':'Temas',
		'deleteimage':'Eliminar imagen',
		'content':'Contenido',
		'url':'URL',
		'entertheorysubtitle':'Ingrese el subtítulo de la teoría',
		'entertheorytitle':'Ingrese el título de la teoría',
		'notopicsincourse':'No hay temas en este curso.',
		'createnewtheory':'Crear nueva teoría',
		'createnewexercise':'Crear nuevo ejercicio',
		'createnewcourse':'Crear nuevo curso',
		'currentcourses':'Cursos actuales',
        'register': 'Registrate', 
		'chooseexercisetype' : "Elija el tipo de ejercicio",
		'exercises' : 'Ejercicios',
		'attemp' : 'Intentos',
		'animation' : 'Animación',
		'selection' :'Selección',
		'labelling' : 'Etiquetado',
		'from':'de',
		'mpr' : 'MPR',
		'test2d' : 'Test 2D',
		'to':'a',
		'image3d' : '3d Image',
		'image2d' : 'Imagen 2D',
		'strategy' : 'Estrategia',
		'time' : 'Tiempo',
		'addexercises' : 'Agregar ejercicios',
		'assignexercises' :'Asignar Ejercicios',
		'continue':'Continuar',
		'students' : 'Estudiantes',
		'login' : 'Iniciar Sesión', 
		'fullpenalty' : 'Penalización completa',
		'partialpenalty': 'Penalización parcial',
		'nopenalty':'Ninguna penalización',
		'logout' : 'Cerrar Sesión',
		'admin' : 'Administrador',
		'profile' : 'Perfil',
		'courses' : 'Cursos',
		'elearningplatform' : 'Plataforma E-Learning',
		'registerintro' : 'Esta es una plataforma creada con la finalidad de enseñar temas como Radiología, RCP y anatomía, entre otros. GILAB, es un grupo de investigación de la Universidad de Girona (con código GRCT0081) y todos los investigadores del GIlab son del Departamento de Ciencias de la Computación, Matemáticas Aplicadas y Estadística de la misma universidad.',
		'registernow':"Registrate ahora",
		'enterasguest' : 'Entrar como invitado',
		'enteremail' : "Introduzca su e-mail",
		'enterusername' : "Introduce su usuario",
		'enterpassword' : "Introduzca su contraseña",
		'enterrepeatpassword' : 'Repita su contraseña',
		'forgotpassword' : '¿Se te olvidó tu contraseña?',
        'cookies': 'Usamos cookies para garantizar que le brindamos la mejor experiencia en nuestro sitio web. También utilizamos cookies para asegurarnos de mostrarle publicidad que sea relevante para usted. Si continúa sin cambiar su configuración, asumiremos que está contento de recibir todas las cookies en el sitio web.', 
    } 
] 
export default language;